import { defineType, defineField } from 'sanity';

export const previewToken = defineType({
  name: 'previewToken',
  title: 'Preview Token',
  type: 'document',
  fields: [
    defineField({
      name: 'token',
      title: 'Token',
      type: 'string',
    }),
    defineField({
      name: 'product',
      title: 'Product',
      type: 'reference',
      to: [{ type: 'product' }]
    }),
    defineField({
      name: 'expiresAt',
      title: 'Expires At',
      type: 'datetime',
    }),
    defineField({
      name: 'generatedBy',
      title: 'Generated By Email',
      type: 'string',
    }),
  ]
});
